### ISSUE TITLE
Insert images

### ISSUE THREAD

**Issue by k06a** [fphilipe/PHFComposeBarView#2]
Is it possible to inline images in text field?
Maybe you have an idea to do so?
I am ready to contribute...

**Comment by sovereignshare** [comment]
It is possible now: 

let attributedString = NSMutableAttributedString(string: self.phfComposeBarView.text + " ");
            let textAttachment = NSTextAttachment();
            textAttachment.image = image;
            
            let oldWidth = image.size.width;
            
            let scaleFactor = oldWidth / (phfComposeBarView.frame.size.width / 2);
            
            textAttachment.image = UIImage(CGImage: image.CGImage, scale: scaleFactor, orientation: UIImageOrientation.Up);
            
            let attrStringWithImage = NSAttributedString(attachment: textAttachment);
            self.imageIndex = countElements(self.phfComposeBarView.text);
            attributedString.replaceCharactersInRange(NSMakeRange(imageIndex, 1), withAttributedString: attrStringWithImage);
            
            phfComposeBarView.textView.attributedText = attributedString;

**Comment by a432511** [comment]
It is possible now: 

            let attributedString = NSMutableAttributedString(string: self.phfComposeBarView.text + " ");
            let textAttachment = NSTextAttachment();
            textAttachment.image = image;
            
            let oldWidth = image.size.width;
            
            let scaleFactor = oldWidth / (phfComposeBarView.frame.size.width / 2);
            
            textAttachment.image = UIImage(CGImage: image.CGImage, scale: scaleFactor, orientation: UIImageOrientation.Up);
            
            let attrStringWithImage = NSAttributedString(attachment: textAttachment);
            self.imageIndex = countElements(self.phfComposeBarView.text);
            attributedString.replaceCharactersInRange(NSMakeRange(imageIndex, 1), withAttributedString: attrStringWithImage);
            
            phfComposeBarView.textView.attributedText = attributedString;

**Comment by k06a** [comment]
@a432511 :+1:
