### ISSUE TITLE
Why is the textView inside a button?

### ISSUE THREAD

**Issue by thisisjeffwong** [fphilipe/PHFComposeBarView#36]
Hi, I was trying to customize the textView's border to be square and clear, but then I discovered that the border was generated by the button that encloses the textView.

I see that the only function of the button is to `becomeFirstResponder`. Why is this necessary? Isn't tapping on the textView enough to cause it to take first responder? 

Having the button that encloses the textview causes some problems with Accessibility, since I cannot really set the label on the button in a non-hacky way.

**Comment by jamesbebbington** [comment]
FYI: The work being done in #63 addresses this issue.
