### ISSUE TITLE
Crash while setting the delegate:  Acessibility?

### ISSUE THREAD

**Issue by acf** [fphilipe/PHFComposeBarView#41]
Hi,

I've just gone live with an app using the excellent PHFComposeBarView.  I've seen a few crashes over the last couple of days when setting the delegate.  I'm suspecting something to do with Accessibility (due both to the word appearing in the crash report, and the fact that it seems to be consistently affecting 2 users, but no-one else).  It's iOS8 only, and affecting both iPhone 5S and 6+.

The crash report is here: http://crashes.to/s/0321516c355  but I've screens hotted the salient piece here:
![2014-10-06_1109](https://cloud.githubusercontent.com/assets/218/4524214/4bb5df0a-4d41-11e4-8a93-d679915fbe65.png)

I'm not expecting you to fix my bugs :-)  But I just wondered if anyone else had seen it and/or figured it out.

Thanks again for a really useful component.

Alan

**Comment by zsk425** [comment]
+1
