### ISSUE TITLE
Is the purpose to mimic the iMessage app 100%?

### ISSUE THREAD

**Issue by dilizarov** [fphilipe/PHFComposeBarView#44]
I have altered the library code in my app a bit to function more as one would expect.

Namely, I altered button enabling:

    - (void)updateButtonEnabled {
        BOOL enabled = [self isEnabled] && [[[[self textView] text] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] length] > 0;
    
        if (_maxCharCount > 0) {
            enabled = [[[[self textView] text] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]] length] <= _maxCharCount;
        }
    
        [[self button] setEnabled:enabled];
    }

I think this functions a lot more as someone would expect. You do nearly all your checks on the trimmed string, so one would expect the button enabling to be the same. In the above, the button is enabled only when the length of the trimmed textView text is greater than 0 and when it is less than the maxCharCount if the maxCharCount was set.

If the purpose is to 100% mimic the iMessage app, then I won't submit a pull-request, just figure this is more intuitive with how one would expect.

**Comment by fphilipe** [comment]
Yes, the idea is to mimic iMessage as close as possible. This functionality can be easily implemented with the delegate messages.
