### ISSUE TITLE
When the keyboard comes up, the composebarview gets offset from the bottom by a few pixels.

### ISSUE THREAD

**Issue by dilizarov** [fphilipe/PHFComposeBarView#45]
Here is a video that illustrates the bug:

https://vid.me/W7rx

**Comment by avitorio** [comment]
Hi @dilizarov,

I'm facing the same problem, I know this post is from over a year ago, but do you still have the solution?

Thanks!

**Comment by dilizarov** [comment]
Hi @avitorio,

To be honest, this happened so long ago I don't even know where to begin with what my solution was.

I think my solution was very hacky though. I had a separate ScrollViewController just for the keyboard that was embedded into the page. Either that, or I may have just used a different library. There are tons!

**Comment by avitorio** [comment]
@dilizarov Yeah man, I understand. Thanks for taking the time to answer. Have a good week! 👍
