### ISSUE TITLE
stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet] check needed

### ISSUE THREAD

**Issue by MattiaConfalonieri** [fphilipe/PHFComposeBarView#46]
Check stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet] needed to prevent only space message sent.

**Comment by MattiaConfalonieri** [comment]
Sorry but i am not able to make a pull request, you need to change 

- (void)updateButtonEnabled {
    BOOL enabled = [self isEnabled] && [[[[self textView] text] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]] length] > 0;
    [[self button] setEnabled:enabled];
}

in PHFComposeBarView.h

Hope this help

**Comment by fphilipe** [comment]
This is intended behavior to mimic the messages app. Not fixing. You can get this functionality using a delegate.
