### ISSUE TITLE
Swift/AutoLayout : Bar stays under keyboard when keyboard is presented

### ISSUE THREAD

**Issue by jerometonnelier** [fphilipe/PHFComposeBarView#47]
Hi there =)

Though I already user PHFComposeBarView successfully in the past, I needed to use it in a swift project, but the ComposeBarView stays under the keyboard all the time.

I didn't have the time to figure out if this was an auto layout issue, or a swift issue (though my first guess would be AutoLayout). Did anyone had the same issue?

Thanks.

**Comment by allaire** [comment]
It's normal, if you check the exemple in the git repo, there is some code to keep the compose bar above the keyboard.

Here some code to get you started:

```swift
    @objc func keyboardWillShowNotification(notification: NSNotification) {
        updateBottomLayoutConstraintWithNotification(notification)
    }
    
    @objc func keyboardWillHideNotification(notification: NSNotification) {
        updateBottomLayoutConstraintWithNotification(notification, constant: 0)
    }
    
    func updateBottomLayoutConstraintWithNotification(notification: NSNotification, constant: CGFloat = CGFloat.max) {
        let userInfo = notification.userInfo!
        var keyboardHeight = userInfo[UIKeyboardFrameEndUserInfoKey]!.CGRectValue().size.height
        let animationDuration = (userInfo[UIKeyboardAnimationDurationUserInfoKey] as! NSNumber).doubleValue
        
        if constant != CGFloat.max {
            keyboardHeight = constant
        } else {
            if let tabBarController = tabBarController {
                keyboardHeight = keyboardHeight - tabBarController.tabBar.frame.height
            }
        }
        
        composeBarViewBottomConstraint.constant = keyboardHeight
        
        UIView.animateWithDuration(animationDuration, animations: { () -> Void in
            self.view.layoutIfNeeded()
        })
    }```

**Comment by jerometonnelier** [comment]
Thanks, I completely forgot about my message ;-)My bad, I did implemented it using constraint OUTLet. Thanks ;-) 


     Le Jeudi 28 mai 2015 2h48, Mathieu Allaire <notifications@github.com> a écrit :
   

 It's normal, if you check the exemple in the git repo, there is some code to keep the compose bar above the keyboard.Here some code to get you started:    @objc func keyboardWillShowNotification(notification: NSNotification) {
        updateBottomLayoutConstraintWithNotification(notification)
    }

    @objc func keyboardWillHideNotification(notification: NSNotification) {
        updateBottomLayoutConstraintWithNotification(notification, constant: 0)
    }

    func updateBottomLayoutConstraintWithNotification(notification: NSNotification, constant: CGFloat = CGFloat.max) {
        let userInfo = notification.userInfo!
        var keyboardHeight = userInfo[UIKeyboardFrameEndUserInfoKey]!.CGRectValue().size.height
        let animationDuration = (userInfo[UIKeyboardAnimationDurationUserInfoKey] as! NSNumber).doubleValue

        if constant != CGFloat.max {
            keyboardHeight = constant
        } else {
            if let tabBarController = tabBarController {
                keyboardHeight = keyboardHeight - tabBarController.tabBar.frame.height
            }
        }

        composeBarViewBottomConstraint.constant = keyboardHeight

        UIView.animateWithDuration(animationDuration, animations: { () -> Void in
            self.view.layoutIfNeeded()
        })
    }```—
