### ISSUE TITLE
autoscroll does not work

### ISSUE THREAD

**Issue by balkarov** [fphilipe/PHFComposeBarView#49]
why not auto scroll when I type and finish line? How do I fix this error?
![2015-08-16 15 04 35](https://cloud.githubusercontent.com/assets/6030335/9293162/2dfb40e8-4428-11e5-923c-e0bec7ee5250.png)

**Comment by fphilipe** [comment]
What do you mean by "finish line"? When you press *enter*? Does this only happen after 5 lines?

**Comment by balkarov** [comment]
eg: http://stackoverflow.com/questions/22315755/ios-7-1-uitextview-still-not-scrolling-to-cursor-caret-after-new-line

**Comment by fphilipe** [comment]
Can't reproduce.
