### ISSUE TITLE
Mutliline text is cut

### ISSUE THREAD

**Issue by engmsaleh** [fphilipe/PHFComposeBarView#51]
I have an issue when I use the composeBar to enter more than a line , the first one is displayed correctly the lines after are being cut and not visible.
Check attached photo
![issue](https://cloud.githubusercontent.com/assets/462150/11187592/b07f6102-8c8f-11e5-8b87-485b626703c4.png)

**Comment by fphilipe** [comment]
I'm sorry, can't really help you. Maybe something with the font size?

**Comment by engmsaleh** [comment]
I have ended up solving it by the following code in the composeBarView delegate
```
- (void)composeBarView:(PHFComposeBarView *)composeBarView
   willChangeFromFrame:(CGRect)startFrame
               toFrame:(CGRect)endFrame
              duration:(NSTimeInterval)duration
        animationCurve:(UIViewAnimationCurve)animationCurve
{
    float diff = (startFrame.size.height - endFrame.size.height);
    CGRect frame = self.tableView.frame;
    frame.size.height += diff;
    self.tableView.frame = frame;
    
    CGRect textViewFrame = composeBarView.textView.frame;
    textViewFrame.size.height -= diff;
    composeBarView.textView.frame = textViewFrame;

}
```

**Comment by fphilipe** [comment]
:+1: Glad you found a solution
