### ISSUE TITLE
Resign First Responder not working with Swift

### ISSUE THREAD

**Issue by justin-nodeboy** [fphilipe/PHFComposeBarView#54]
Hey

For some reason I can never get the view/keyboard to disappear with resignFirstResponder or endEditing. I manage to make it go when the view closes but only by doing UIApplication.sharedApplication().sendAction(Selector("resignFirstResponder"), to: nil, from: nil, forEvent: nil) which is pretty aggressive.

Any thoughts on what my be causing it to stick? I am using Swift 2.1.1 and iOS 9.2

**Comment by fphilipe** [comment]
Sorry, I have no clue what could be causing this. Maybe ask on StackOverflow.

**Comment by mreilly4** [comment]
I am having the same problem

**Comment by MikeSalvador** [comment]
Did you guys ever figure this out?

**Comment by justin-nodeboy** [comment]
@MikeSalvador Nope, I ended up using a different framework in the end. https://github.com/aryaxt/TextInputBar
