### ISSUE TITLE
White view over the UITextView not showing the entered text

### ISSUE THREAD

**Issue by halbano** [fphilipe/PHFComposeBarView#57]
That's my issue, any help is really apreciated. 

Image attached for better understanding. 

Any help is really appreciated 

![screenshot 2016-07-01 03 00 37](https://cloud.githubusercontent.com/assets/5341623/16513071/0af280c8-3f38-11e6-8584-1fa43ec09ac7.png)

**Comment by fphilipe** [comment]
Have you looked at the example app? Does this happen there as well? Maybe you can check what is different from the example.

**Comment by halbano** [comment]
Yeah, the code I'm using is almost a copy paste of that sample app. It's really weird. In addition I cannot debug the interface :/

**Comment by fphilipe** [comment]
Sorry, I can't really help you. Try stripping any differences from the example app until it works. Good luck!

**Comment by halbano** [comment]
If you has to guess what can be occurring what you would say? Seems to be something with white background color instead of clear over the UITextView.

**Comment by fphilipe** [comment]
@halbano Sorry, no idea.
