### ISSUE TITLE
Globally selected text &  Image paste

### ISSUE THREAD

**Issue by balkrishanyadav** [fphilipe/PHFComposeBarView#60]
Hello,

I working PHFComposeBarView for chat application.  I want to use paste option in text view if i already selected image or text from application or out of application.

**Comment by fphilipe** [comment]
Sorry, it does not support images.

**Comment by balkrishanyadav** [comment]
OK, @fphilipe But Please let me know for the text so i can achieve partially success. Thanks

**Comment by fphilipe** [comment]
You mean how to paste text? That should work out of the box by long pressing the text field until the standard black pop menu appears with the "Paste" option.

**Comment by balkrishanyadav** [comment]
For Example we are currently open iMessage and copy some text form here.. after that we open our app and want to paste copied text.

**Comment by fphilipe** [comment]
> For Example we are currently open iMessage and copy some text form here.. after that we open our app and want to paste copied text.

I don't understand. That doesn't work?
