### ISSUE TITLE
Regarding Default size increase when load composebar

### ISSUE THREAD

**Issue by balkrishanyadav** [fphilipe/PHFComposeBarView#61]
Hello,

I am using compose bar for my chat application. Application is responsive from as per default font style from setting(Font Zoom Increase Decrease) style. So If font size is larger 53 then change compose bar view in height as default UI for single line text message.

Thanks,

**Comment by fphilipe** [comment]
Hi. Not sure I follow. Are you reporting a problem?

**Comment by balkrishanyadav** [comment]
No, Actually I am looking for solution for achieve my implementation goal.

Thanks

**Comment by fphilipe** [comment]
You want the initial height to match your font size?

**Comment by balkrishanyadav** [comment]
yes, and change initial height as per font size...

**Comment by fphilipe** [comment]
I don't think this is possible. At least not without modifying the implementation. Sorry, can't help you more than that 😊 Good luck!

**Comment by balkrishanyadav** [comment]
Ok, Thanks..
