### ISSUE TITLE
UIBarStyleBlackTranslucent?

### ISSUE THREAD

**Issue by JosephShenton** [fphilipe/PHFComposeBarView#65]
Is it possible you implemented a dark version of this? Because It would help a lot as you can see in my screenshot.
![img_7215](https://user-images.githubusercontent.com/12966231/27072726-b8a6a242-5064-11e7-97c8-e42f66727ce3.PNG)

**Comment by fphilipe** [comment]
I'm not implementing this. But I'm open to including this. PRs welcome 😉

**Comment by JosephShenton** [comment]
Ok! I’ll add it now!
